#input_data_training: 'C:\E\Data\TUM\Semester 3\Lab Course DLCV\deep analytics\data\bball_google_handlabeled\tfrecords\sequence.train.record'
#input_data_testing: 'C:\E\Data\TUM\Semester 3\Lab Course DLCV\deep analytics\data\bball_google_handlabeled\tfrecords\sequence.train.record'

input_data_training: '/work/deepanalytics/bball_google_handlabeled/tfrecords/sequence.train.record'
input_data_testing: '/work/deepanalytics/bball_google_handlabeled/tfrecords/sequence.train.record'

#faster_rcnn_graph: 'C:\E\Data\TUM\Semester 3\Lab Course DLCV\deep analytics\data\bball_google_handlabeled\faster_rcnn_graph\output_inference_graph.pb'

faster_rcnn_graph: '/work/deepanalytics/bball_google_handlabeled/faster_rcnn_graph/output_inference_graph.pb'

train_summaries: 'summaries/train'
checkpoints: 'checkpoints'
results: 'results'

summary_interval: 1
result_interval: 10

# TODO: Unused.
save_interval: 200
validation_interval: 500

resize_height: 480
resize_width: 854

batch_size: 1
epochs: 5000
backprop_step_size: 30 # Defines the width of the unrolled rnn graph.
learning_rate: 0.001

# TODO: Unused.
lstm_layers: 1
state_size: 1500

lstm_cls_layers: 1
lstm_cls_state_size: 1500
lstm_cls_learning_rate: 0.001